import type { Cs2ItemView } from "@/lib/cs2/types";
import { SAMPLE_CS2_IMAGE_URLS } from "@/lib/cs2/imageIndex";

const now = new Date("2026-06-04T12:00:00.000Z").toISOString();

function cents(value: number) {
  return Math.round(value * 100);
}

function candles(base: number, marketName = "BUFF163") {
  return Array.from({ length: 14 }, (_, index) => {
    const drift = (index - 7) * 0.006;
    const wave = Math.sin(index / 2) * 0.018;
    const close = Math.max(1, base * (1 + drift + wave));
    return {
      provider: "sample",
      marketName,
      interval: "1d" as const,
      openCents: cents(close * 0.982),
      highCents: cents(close * 1.026),
      lowCents: cents(close * 0.961),
      closeCents: cents(close),
      volume: 24 + index * 3,
      startsAt: new Date(Date.UTC(2026, 4, 22 + index)).toISOString(),
    };
  });
}

export const SAMPLE_CS2_ITEMS: Cs2ItemView[] = [
  {
    id: "sample-ak-redline-ft",
    marketHashName: "AK-47 | Redline (Field-Tested)",
    itemType: "skin",
    category: "rifle",
    rarity: "classified",
    exterior: "Field-Tested",
    collection: "The Phoenix Collection",
    imageUrl: SAMPLE_CS2_IMAGE_URLS.akRedline,
    tradable: true,
    bestAskCents: cents(28.42),
    bestBidCents: cents(27.91),
    chineseAskCents: cents(26.72),
    globalAskCents: cents(28.42),
    spreadPercent: -5.98,
    snapshots: [
      {
        provider: "sample",
        marketName: "BUFF163",
        marketRegion: "china",
        currency: "USD",
        askCents: cents(26.72),
        bidCents: cents(26.1),
        medianCents: cents(27.03),
        askVolume: 2214,
        bidVolume: 402,
        salesVolume24h: 188,
        liquidityScore: 94,
        observedAt: now,
        sourceUrl: "https://buff.163.com",
      },
      {
        provider: "sample",
        marketName: "CSFloat",
        marketRegion: "global",
        currency: "USD",
        askCents: cents(28.42),
        bidCents: cents(27.91),
        medianCents: cents(28.8),
        askVolume: 516,
        bidVolume: 88,
        salesVolume24h: 47,
        liquidityScore: 81,
        observedAt: now,
        sourceUrl: "https://csfloat.com",
      },
    ],
    candles: candles(26.72),
  },
  {
    id: "sample-awp-asiimov-ft",
    marketHashName: "AWP | Asiimov (Field-Tested)",
    itemType: "skin",
    category: "sniper rifle",
    rarity: "covert",
    exterior: "Field-Tested",
    collection: "The Phoenix Collection",
    imageUrl: SAMPLE_CS2_IMAGE_URLS.awpAsiimov,
    tradable: true,
    bestAskCents: cents(126.12),
    bestBidCents: cents(123.3),
    chineseAskCents: cents(119.94),
    globalAskCents: cents(126.12),
    spreadPercent: -4.9,
    snapshots: [
      {
        provider: "sample",
        marketName: "YouPin898",
        marketRegion: "china",
        currency: "USD",
        askCents: cents(119.94),
        bidCents: cents(117.4),
        medianCents: cents(121.03),
        askVolume: 936,
        bidVolume: 155,
        salesVolume24h: 61,
        liquidityScore: 89,
        observedAt: now,
        sourceUrl: "https://www.youpin898.com",
      },
      {
        provider: "sample",
        marketName: "Skinport",
        marketRegion: "europe",
        currency: "USD",
        askCents: cents(126.12),
        bidCents: null,
        medianCents: cents(129.52),
        askVolume: 118,
        bidVolume: null,
        salesVolume24h: 19,
        liquidityScore: 64,
        observedAt: now,
        sourceUrl: "https://skinport.com",
      },
    ],
    candles: candles(119.94, "YouPin898"),
  },
  {
    id: "sample-butterfly-doppler-fn",
    marketHashName: "★ Butterfly Knife | Doppler (Factory New)",
    itemType: "knife",
    category: "knife",
    rarity: "covert",
    exterior: "Factory New",
    collection: "Doppler Finishes",
    imageUrl: SAMPLE_CS2_IMAGE_URLS.butterflyDoppler,
    tradable: true,
    bestAskCents: cents(3978.66),
    bestBidCents: cents(3840.4),
    chineseAskCents: cents(3978.66),
    globalAskCents: cents(4149.99),
    spreadPercent: -4.13,
    snapshots: [
      {
        provider: "sample",
        marketName: "YouPin898",
        marketRegion: "china",
        currency: "USD",
        askCents: cents(3978.66),
        bidCents: cents(3840.4),
        medianCents: cents(4012.28),
        askVolume: 47,
        bidVolume: 18,
        salesVolume24h: 6,
        liquidityScore: 76,
        observedAt: now,
        sourceUrl: "https://www.youpin898.com",
      },
      {
        provider: "sample",
        marketName: "CSFloat",
        marketRegion: "global",
        currency: "USD",
        askCents: cents(4149.99),
        bidCents: cents(3950),
        medianCents: cents(4215.6),
        askVolume: 22,
        bidVolume: 4,
        salesVolume24h: 2,
        liquidityScore: 57,
        observedAt: now,
        sourceUrl: "https://csfloat.com",
      },
    ],
    candles: candles(3978.66, "YouPin898"),
  },
  {
    id: "sample-sport-gloves-pandora-ft",
    marketHashName: "★ Sport Gloves | Pandora's Box (Field-Tested)",
    itemType: "gloves",
    category: "gloves",
    rarity: "extraordinary",
    exterior: "Field-Tested",
    collection: "Glove Case",
    imageUrl: SAMPLE_CS2_IMAGE_URLS.sportGlovesPandora,
    tradable: true,
    bestAskCents: cents(6450),
    bestBidCents: cents(6210),
    chineseAskCents: cents(6450),
    globalAskCents: cents(6890),
    spreadPercent: -6.39,
    snapshots: [
      {
        provider: "sample",
        marketName: "BUFF163",
        marketRegion: "china",
        currency: "USD",
        askCents: cents(6450),
        bidCents: cents(6210),
        medianCents: cents(6521),
        askVolume: 18,
        bidVolume: 9,
        salesVolume24h: 1,
        liquidityScore: 48,
        observedAt: now,
        sourceUrl: "https://buff.163.com",
      },
      {
        provider: "sample",
        marketName: "DMarket",
        marketRegion: "global",
        currency: "USD",
        askCents: cents(6890),
        bidCents: null,
        medianCents: cents(6995),
        askVolume: 7,
        bidVolume: null,
        salesVolume24h: 0,
        liquidityScore: 25,
        observedAt: now,
        sourceUrl: "https://dmarket.com",
      },
    ],
    candles: candles(6450),
  },
  {
    id: "sample-sticker-crown",
    marketHashName: "Sticker | Crown (Foil)",
    itemType: "sticker",
    category: "sticker",
    rarity: "exotic",
    exterior: null,
    collection: "Sticker Capsule 2",
    imageUrl: SAMPLE_CS2_IMAGE_URLS.crownFoil,
    tradable: true,
    bestAskCents: cents(895.4),
    bestBidCents: cents(861.9),
    chineseAskCents: cents(895.4),
    globalAskCents: cents(949.99),
    spreadPercent: -5.75,
    snapshots: [
      {
        provider: "sample",
        marketName: "BUFF163",
        marketRegion: "china",
        currency: "USD",
        askCents: cents(895.4),
        bidCents: cents(861.9),
        medianCents: cents(908.2),
        askVolume: 122,
        bidVolume: 34,
        salesVolume24h: 8,
        liquidityScore: 69,
        observedAt: now,
        sourceUrl: "https://buff.163.com",
      },
      {
        provider: "sample",
        marketName: "Steam",
        marketRegion: "global",
        currency: "USD",
        askCents: cents(949.99),
        bidCents: cents(918.11),
        medianCents: cents(951.22),
        askVolume: 42,
        bidVolume: 12,
        salesVolume24h: 3,
        liquidityScore: 41,
        observedAt: now,
        sourceUrl: "https://steamcommunity.com/market",
      },
    ],
    candles: candles(895.4),
  },
  {
    id: "sample-operator-number-k",
    marketHashName: "Sir Bloody Miami Darryl | The Professionals",
    itemType: "operator",
    category: "agent",
    rarity: "master",
    exterior: null,
    collection: "Operation Broken Fang Agents",
    imageUrl: SAMPLE_CS2_IMAGE_URLS.miamiDarryl,
    tradable: true,
    bestAskCents: cents(92.18),
    bestBidCents: cents(88.5),
    chineseAskCents: cents(88.5),
    globalAskCents: cents(92.18),
    spreadPercent: -3.99,
    snapshots: [
      {
        provider: "sample",
        marketName: "BUFF163",
        marketRegion: "china",
        currency: "USD",
        askCents: cents(88.5),
        bidCents: cents(86.2),
        medianCents: cents(89.4),
        askVolume: 301,
        bidVolume: 80,
        salesVolume24h: 24,
        liquidityScore: 78,
        observedAt: now,
        sourceUrl: "https://buff.163.com",
      },
      {
        provider: "sample",
        marketName: "BitSkins",
        marketRegion: "global",
        currency: "USD",
        askCents: cents(92.18),
        bidCents: null,
        medianCents: cents(94.1),
        askVolume: 37,
        bidVolume: null,
        salesVolume24h: 5,
        liquidityScore: 52,
        observedAt: now,
        sourceUrl: "https://bitskins.com",
      },
    ],
    candles: candles(88.5),
  },
];
